name: Test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: package
    env:
      ENDPOINT: ${{ secrets.ENDPOINT }}
      KEY: ${{ secrets.KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: |
          npm ci
      - name: Run tests
        run: |
          npm test